### Numpy ndarray

**ndarray : N 차원(dimension) 배열(array) 객체**

In [1]:
import numpy as np

**ndarray 생성**
* Numpy 모듈의 array( ) 함수로 생성
* 인자로 주로 python list 또는 ndarray 입력

**ndarray 형태와 차원**
* 형태는 ndarray.shape 
* 차원은 ndarray.ndim

In [2]:
list1 = [1,2,3]
print('list1 type:', type(list1))

array1 = np.array(list1)
print(array1)
print('array1 type:', type(array1))
print('array1 형태:', array1.shape)

array2 = np.array([[1,2,3],
                 [4,5,6]])
print(array2)
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print(array3)
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)


list1 type: <class 'list'>
[1 2 3]
array1 type: <class 'numpy.ndarray'>
array1 형태: (3,)
[[1 2 3]
 [4 5 6]]
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
[[1 2 3]]
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


**ndarray의 shape**은 axis0, axis1, axis2와 같이 **axis 단위**로 부여됨

**ndarray 타입**
* ndarray내의 데이터 값은 숫자 값, 문자열 값, 불리언 모두 가능
* 연산 특성상 같은 데이터 타입만 가능함, 즉 한 개의 ndarray객체에 int와 float가 함께 있을 수 없음
* 만약 array 생성할 때 다른 dtype을 같이 입력하면 자동 type 변환됨
* ndarray.dtype으로 확인

In [4]:
print(array1, array1.dtype)

[1 2 3] int32


In [5]:
# 자동 type 변환의 예

array4 = np.array([1, 2, 'test'])
print(array4, array4.dtype)

array5 = np.array([1, 2, 3.0])
print(array5, array5.dtype)

# array4의 1, 2가 문자형으로 바뀌고, array5의 1, 2가 실수형으로 바뀜

['1' '2' 'test'] <U11
[1. 2. 3.] float64


**ndarray 타입 변환**
* astype( )을 이용하여 원하는 type으로 변환 가능 (대용량 데이터 다룰 시 메모리 절약을 위해서 64bit float형을 8bit 또는 16bit의 integer 형으로 변환하는 등, 형변환을 특히 고려해야함)

In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_int, array_int.dtype)
print(array_float, array_float.dtype)

[1 2 3] int32
[1. 2. 3.] float64


In [7]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [8]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int.dtype)

[1 2 3] int32


**ndarray를 편리하게 생성하기 - arange, zeros, ones**
* 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화 생성해야 한 경우, arange( ), zeros( ), ones( )를 이용해 생성 가능
* 주로 테스트용 데이터를 만들거나 데이터를 일괄적으로 초기화해야 할 경우에 사용

In [9]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.shape, sequence_array.dtype, sequence_array.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,) int32 1


In [10]:
zero_array = np.zeros ((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**ndarray의 차원과 크기를 변경하기 - reshape( )**
* 원하는 특정 차원 및 형태로 변환함

In [11]:
array1 = np.arange(10)
print(array1)

# (2, 5) shape으로 변환
array2 = array1.reshape(2, 5)
print(array2)

# (5, 2) shape으로 변환
array3 = array2.reshape(5, 2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
# (-1, 5) shape으로 변환
array4 = array1.reshape(-1, 5)
print(array4)
print(array4.shape)

# (5, -1) shape으로 변환
array5 = array1.reshape(5, -1)
print(array5)
print(array5.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [14]:
# 3차원 ndarray를 2차원 ndarray로 변환하되 칼럼 갯수는 1
array6 = array3d.reshape(-1, 1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

# 1차원 ndarray를 2차원 ndarray로 변환화되 칼럼 갯수는 1
array7 = array1.reshape(-1, 1)
print('array6:\n',array7.tolist())
print('array6 shape:',array7.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [15]:
# 3차원 array를 1차원으로 변환
array1d = array3d.reshape(-1,)
print(array1d)

[0 1 2 3 4 5 6 7]


**ndarray indexing**

* 특정 위치 단일값 추출
* slicing (:) : 연속되게 추출
* fancy indexing : 특정 위치 여러 개, list나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarry 반환
* boolean indexing : 조건을 걸어서, 조건 필터링과 추출을 동시에 할 수 있기 때문에 자주 사용됨

In [28]:
# 단일 값 추출 - 1차원 ndarray
array1 = np.arange(start=1, stop=10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
print(array1[3])
print(array1[-2])
print(array1[-1])

4
8
9


In [18]:
# 단일 값 추출 - 2차원 ndarray
array2 = array1.reshape(3,3)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(array2[0,0])
print(array2[0,1])
print(array2[1,0])
print(array2[2,2])

1
2
4
9


In [20]:
# slicing - 1차원 ndarray

print(array1[:])
print(array1[:3])
print(array1[3:])
print(array1[0:3])

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3]


In [21]:
# slicing - 2차원 ndarray

print(array2[:,:])
print(array2[0:2,0:2])
print(array2[1:3,0:3])
print(array2[:2,0])  ## 결과 : 1차원 array (shape : (2, ))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[1 4]


In [29]:
print(array2[0])
print('array2[0] shape:', array2[0].shape)
print(array2[1])
print('array2[1] shape:', array2[1].shape)

[1 2 3]
array2[0] shape: (3,)
[4 5 6]
array2[1] shape: (3,)


In [36]:
# fancy indexing

print(array2)

array3 = array2[[0,1],2]
print(array3.tolist())

array4 = array2[0:2,[0,1]]
print(array4.tolist())

array5 = array2[[0,1]]
print(array5.tolist())

array6 = array2[:,[0,1]]
print(array6.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]
[[1, 2], [4, 5], [7, 8]]


In [40]:
# boolean indexing

print(array1)

array2 = array1[array1>5]
print(array2)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


**ndarray sort( ), argsort( )**

배열의 정렬
* np.sort(ndarray) : 인자로 들어온 행렬은 그대로 유지한 채 원래 행렬의 정렬된 행렬을 반환 
* ndarray.sort( ) : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 none
* 모두 기본적으로 **오름차순**으로 정렬되며, **내림차순**으로 정렬하기 위해서는 [::-1]을 적용한다. 
* argsort( ) : 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환함


In [46]:
org_array = np.array([ 3, 1, 9, 5]) 

# np.sort()
array_sorted = np.sort(org_array)
print('org_array:', org_array) # 원 행렬은 유지
print('array_sorted:', array_sorted)

# ndarray.sort()
org_array.sort()
print('org_array:', org_array) # 원 행렬이 변환됨

# 내림차순 정렬
org_array[::-1].sort()
print('org_array:', org_array)
array_desc = np.sort(org_array)[::-1]
print('array_desc:', array_desc)

org_array: [3 1 9 5]
array_sorted: [1 3 5 9]
org_array: [1 3 5 9]
org_array: [9 5 3 1]
array_desc: [9 5 3 1]


In [48]:
# sort by row or column

array2d = np.array([[8,12],
                    [7,1]])
print(array2d)

sort_array_by_row = np.sort(array2d, axis = 0)
print(sort_array_by_row)

sort_array_by_col = np.sort(array2d, axis = 1)
print(sort_array_by_col)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [50]:
# argsort()

org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 배열의 인덱스 : \n', sort_indices_desc)

행렬 내림차순 정렬 시 원본 배열의 인덱스 : 
 [2 3 0 1]


In [68]:
# argsort() 활용 예시

name_array = np.array(['Amy', 'Bly', 'Coy', 'Diy', 'Ely'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['Amy' 'Coy' 'Ely' 'Bly' 'Diy']


**선형대수 연산 - 행렬내적**
* np.dot(A,B)
* np.transpose(A)

In [70]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [71]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
