# Pandas

행과 열의 2차원 정형 데이터 다루기에 용이


### 주요구성요소
* dataframe(row x column 2D data set)
* series(1개의 column 값으로만 구성된 1D data set)
* index(df, series의 고유한 key값 객체)

In [1]:
import pandas as pd

In [2]:
titanic_df = pd.read_csv('train.csv')
print(type(titanic_df))
titanic_df

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [4]:
titanic_df.tail(3)

PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

df를 code 가운데에서 출력하고 싶다면 print 대신 **display(df)**

In [5]:
pd.set_option('display.max_rows', 1000) # 출력하고 싶은 행의 최대 수 설정
pd.set_option('display.max_colwidth', 100) # 출력하고 싶은 열의 너비 설정
pd.set_option('display.max_columns', 100) # 출력하고 싶은 열의 최대 수 설정

In [6]:
titanic_df.shape

(891, 12)

### DataFrame 생성

In [7]:
dic1 = {'이름' : ['기범', '민호', '태민', '진기'],
        '년도' : [1991, 1991, 1993, 1989],
        '동물' : ['햄스터', '다람쥐', '병아리', '토끼']
       }

# 딕셔너리를 DataFrame으로 변환
df = pd.DataFrame(dic1)
display(df)


# 새로운 컬럼명을 추가
df = pd.DataFrame(dic1, columns=["이름", "년도", "동물", "나이"])
display(df)


# 인덱스를 새로운 값으로 할당. 
df = pd.DataFrame(dic1, index=['one','two','three','four'])
display(df)

이름    년도   동물
0  기범  1991  햄스터
1  민호  1991  다람쥐
2  태민  1993  병아리
3  진기  1989   토끼

이름    년도   동물   나이
0  기범  1991  햄스터  NaN
1  민호  1991  다람쥐  NaN
2  태민  1993  병아리  NaN
3  진기  1989   토끼  NaN

이름    년도   동물
one    기범  1991  햄스터
two    민호  1991  다람쥐
three  태민  1993  병아리
four   진기  1989   토끼

#### column & indexes

In [8]:
print("columns:",titanic_df.columns)
print("index:",titanic_df.index)

# print("index value:", titanic_df.index.values)

columns: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
index: RangeIndex(start=0, stop=891, step=1)


#### info( )
DataFrame내의 컬럼명, 데이터 타입, Null건수, 데이터 건수 정보를 제공

In [9]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


#### describe( )
데이터값들의 평균,표준편차,4분위 분포도를 제공. (숫자형 컬럼들에 대해서)

In [10]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

#### value_counts()

* 개별 데이터 값 별로 몇 건이 있는지 세어줌.
* Null 값을 포함할지 여부를 dropna 인자로 판단 (default : True : 이 경우 Null값 무시하고 개별 데이터 값의 건수를 계산)

In [11]:
count_class = titanic_df['Pclass'].value_counts()
count_class

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [12]:
titanic_df['Pclass'].head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [13]:
# dropna

print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna = False))

S    644
C    168
Q     77
Name: Embarked, dtype: int64
S      644
C      168
Q       77
NaN      2
Name: Embarked, dtype: int64


In [14]:
titanic_df[['Pclass','Embarked']].value_counts()

Pclass  Embarked
3       S           353
2       S           164
1       S           127
        C            85
3       Q            72
        C            66
2       C            17
        Q             3
1       Q             2
dtype: int64

### DataFrame과 list, dictionary, numpy ndarray 상호변환

* list, dict, ndarray ====> dataframe

In [15]:
import numpy as np

In [18]:
col_name1=['col1']
list1 = [1,2,3]
array1 = np.array(list1)

print('array1 shape:', array1.shape)

# list를 df로
df_list1 = pd.DataFrame(list1, columns = col_name1)
# ndarray를 df로
df_array1 = pd.DataFrame(array1, columns = col_name1)

print(df_list1)
print(df_array1)

array1 shape: (3,)
   col1
0     1
1     2
2     3
   col1
0     1
1     2
2     3


In [19]:
# 3개의 칼럼명이 필요한 경우
col_name2 = ['col1', 'col2','col3']

# 2행 by 3열 형태의 list와 ndarray를 df로
list2 = [[1,2,3],
         [11,12,13]]
array2 = np.array(list2)

print('array2 shape:', array2.shape)

df_list2 = pd.DataFrame(list2, columns = col_name2)
df_array2 = pd.DataFrame(array2, columns = col_name2)

print(df_list2)
print(df_array2)

array2 shape: (2, 3)
   col1  col2  col3
0     1     2     3
1    11    12    13
   col1  col2  col3
0     1     2     3
1    11    12    13


In [20]:
# key는 column명으로 매핑, value는 list형 또는 ndarray
dict = {'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    22    33


* dataframe =====> ndarray, list, dict

In [21]:
# df ==> ndarray 변환
array3 = df_dict.values
print('df_dict.values 타입:', type(array3))
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'>
[[ 1  2  3]
 [11 22 33]]


In [22]:
# df ==> list 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

# df ==> dict 변환
dict3 = df_dict.to_dict('list')
print('df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.to_dict()

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]
df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


{'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}}

### DataFrame의 칼럼 데이터 세트 생성 및 수정

In [24]:
titanic_df['Age_0'] = 0
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

### DataFrame 데이터 삭제
**axis**에 따른 삭제
* row 삭제 : axis = 0, col 삭제 : axis = 1
* 원본 df는 유지하고 drop된 df를 새롭게 객체 변수로 받고 싶다면 inplace=False로 설정
* 원본 df에 직접 drop된 결과를 적용할 경우에는 inplace=True를 적용
* 아니면 원본 df와 동일한 객체로 저장

In [25]:
titanic_drop_df = titanic_df.drop('Age_0', axis=1 )
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      220.0          2  
1      0          PC 17599  71.2833   C85        C      380.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      260.0          1

In [26]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

In [27]:
titanic_df.drop('Age_0', axis=1, inplace=True)
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      220.0          2  
1      0          PC 17599  71.2833   C85        C      380.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      260.0          1

In [28]:
# 여러 열을 삭제할 때, column명을 적는다. 
titanic_df.drop(['Age_by_10', 'Family_No'], axis=1, inplace=True)
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [29]:
# 여러 행을 삭제할 때, index를 적는다
titanic_df.drop([0,1,2], axis=0, inplace=True)
titanic_df.head(3)

PassengerId  Survived  Pclass  \
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   
5                              Moran, Mr. James    male   NaN      0      0   

   Ticket     Fare Cabin Embarked  
3  113803  53.1000  C123        S  
4  373450   8.0500   NaN        S  
5  330877   8.4583   NaN        Q

### Index 객체

In [30]:
titanic_df = pd.read_csv('train.csv')
indexes = titanic_df.index
print(indexes)
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

RangeIndex(start=0, stop=891, step=1)
<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [31]:
# index의 값을 변경할 수는 없다.
indexes[0] = 5

TypeError: Index does not support mutable operations

**reset_index( )**

In [32]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [34]:
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [33]:
titanic_df['Pclass'].value_counts().reset_index()

index  Pclass
0      3     491
1      1     216
2      2     184

In [35]:
new_value_counts_01 = titanic_df['Pclass'].value_counts().reset_index()
new_value_counts_01.rename(columns={'index':'Pclass', 'Pclass':'Pclass_count'})

Pclass  Pclass_count
0       3           491
1       1           216
2       2           184

### DataFrame 인덱싱 및 필터링

* df의 [ ] 연산자

In [3]:
# DataFrame객체에서 []연산자내에 한개의 컬럼만 입력하면 Series 객체를 반환  
series = titanic_df['Name']
print(series.head(3))
print("## type:",type(series), 'shape:', series.shape)

# DataFrame객체에서 []연산자내에 여러개의 컬럼을 리스트로 입력하면 그 컬럼들로 구성된 DataFrame 반환  
filtered_df = titanic_df[['Name', 'Age']]
display(filtered_df.head(3))
print("## type:", type(filtered_df), 'shape:', filtered_df.shape)

# DataFrame객체에서 []연산자내에 한개의 컬럼을 리스트로 입력하면 한개의 컬럼으로 구성된 DataFrame 반환 
one_col_df = titanic_df[['Name']]
display(one_col_df.head(3))
print("## type:", type(one_col_df), 'shape:', one_col_df.shape)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
Name: Name, dtype: object
## type: <class 'pandas.core.series.Series'> shape: (891,)


Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0

## type: <class 'pandas.core.frame.DataFrame'> shape: (891, 2)


Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina

## type: <class 'pandas.core.frame.DataFrame'> shape: (891, 1)


In [4]:
# Boolean Indexing
titanic_df[ titanic_df['Pclass'] == 3].head(3)

PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  
0      1      0         A/5 21171  7.250   NaN        S  
2      0      0  STON/O2. 3101282  7.925   NaN        S  
4      0      0            373450  8.050   NaN        S

* df의 iloc[ ] 연산자

In [6]:
titanic_df.iloc[0,3]

'Braund, Mr. Owen Harris'

In [7]:
# iloc 안에 이렇게 직접 열 이름을 넣으면 오류가 발생함

titanic_df.iloc[0, 'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types