## Data Encoding

### Label Encoding

In [1]:
from sklearn.preprocessing import LabelEncoder

# 변환하고자 하는 카테고리 데이터를 list 형태로 정의!
items=['사과', '딸기', '포도', '포도', '바나나']

# LabelEncoder를 객체로 생성
encoder = LabelEncoder()
# fit(), transform()으로 인코딩 수행
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [2 0 3 3 1]


In [2]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['딸기' '바나나' '사과' '포도']


In [3]:
print('디코딩 원본 값:', encoder.inverse_transform([2,0,3,3,1]))

디코딩 원본 값: ['사과' '딸기' '포도' '포도' '바나나']


### One-Hot Encoding

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [6]:
items=['사과', '딸기', '포도', '포도', '바나나']

# 2차원 ndarray로 변환
items = np.array(items).reshape(-1,1)
items

# OneHotEncoder를 객체로 생성
oh = OneHotEncoder()
oh.fit(items)
oh_labels = oh.transform(items)

# OneHotEncoder로 변환한 결과는 희소행렬(Sparse Matrix)이므로 toarray()를 이용하여 밀집행렬(Dense Matrix)로 변환
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
원-핫 인코딩 데이터 차원
(5, 4)


##### pd.get_dummies( )

- Pandas 데이터프레임 내에서 특정 열에 대해 원-핫 인코딩을 간단하게 수행할 때 유용합니다. 
하지만, 데이터프레임 내의 범주형 열에 대해서만 변환을 수행할 수 있습니다. 

In [7]:
import pandas as pd

df = pd.DataFrame({'item': ['사과', '딸기', '포도', '바나나'],
                    'price': [3000, 1000, 2000, 1000]})
df

item  price
0   사과   3000
1   딸기   1000
2   포도   2000
3  바나나   1000

In [8]:
pd.get_dummies(df)

price  item_딸기  item_바나나  item_사과  item_포도
0   3000        0         0        1        0
1   1000        1         0        0        0
2   2000        0         0        0        1
3   1000        0         1        0        0

In [13]:
# df에서 column으로 OneHotEncoder 쓰는 방법

from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder()
encoder = oh.fit_transform(df['item'].values.reshape(-1,1)).toarray() # 인코딩 하기 전에 2차원 데이터로 변환

df_OneHot = pd.DataFrame(encoder, columns = [str(oh.categories_[0][i]) for i in range (len(oh.categories_[0]))])

df1 = pd.concat([df, df_OneHot], axis=1)
df1

item  price   딸기  바나나   사과   포도
0   사과   3000  0.0  0.0  1.0  0.0
1   딸기   1000  1.0  0.0  0.0  0.0
2   포도   2000  0.0  0.0  0.0  1.0
3  바나나   1000  0.0  1.0  0.0  0.0

In [22]:
oh.categories_

[array(['딸기', '바나나', '사과', '포도'], dtype=object)]

## Feature Scaling

### StandardScaler (정규화)

In [23]:
from sklearn.datasets import load_iris
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [24]:
# scaling 하기 전 피쳐별 평균과 분산

print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [30]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()
# fit(), transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

type(iris_scaled)

numpy.ndarray

In [32]:
# transform( )시 scale 변환된 데이터 셋이 numpy ndarray로 반환되기 때문에 DataFrame으로 변환
iris_scaled_df = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

# scaling 후 피쳐별 평균과 분산

print(iris_scaled_df.mean())
print(iris_scaled_df.var())
iris_scaled_df.head()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

### MinMaxScaler (표준화)

In [33]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# fit(), transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최소 값')
print(iris_df_scaled.min())
print('\nfeature들의 최대 값')
print(iris_df_scaled.max())

feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


**Scaler를 이용하여 train/test data에 fit(), transform(), fit_transform() 적용 시 유의사항**

In [34]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0 부터 10까지, 테스트 데이터는 0 부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1, 1)로 차원 변경
train_array = np.arange(0, 11).reshape(-1, 1)
test_array =  np.arange(0, 6).reshape(-1, 1)

In [36]:
print(train_array)
print(test_array)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [37]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print(train_array.reshape(-1))
print(train_scaled.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [38]:
# wrong scaling
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print(test_array.reshape(-1))
print(test_scaled.reshape(-1))

[0 1 2 3 4 5]
[0.  0.2 0.4 0.6 0.8 1. ]


In [39]:
# correct scaling 1

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

# test_array에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform() 만으로 변환해야 함. 
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]


In [41]:
# correct scaling 2 (fit + transform 한번에 "fit_transform()")

scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

# test_array에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform() 만으로 변환해야 함. 
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]


**결론**

1. 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리한다. 
2. 1이 여의치 않다면 테스트 데이터 변환 시에는 fit()이나 fit_transform()을 적용하지 않고 학습 데이터로 이미 fit()된 Scaler 객체를 이용해 transform()으로 변환한다. 