In [26]:
import numpy as np
import pandas as pd

from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier


import warnings
warnings.filterwarnings('ignore')

In [2]:
names = ['sepal-length', 'sepal-width','petal-length','pedal-width','class']
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
dataset = pd.read_csv(url, names=names)

dataset.head()

sepal-length  sepal-width  petal-length  pedal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [27]:
X = dataset.iloc[:,:4].values
y = dataset.iloc[:,4].values
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

std_sc = StandardScaler()
X_train = std_sc.fit_transform(X_train)
X_test = std_sc.transform(X_test)

In [28]:
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [29]:
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=50)

In [30]:
# Evaluating the Algorithm
y_pred = knn.predict(X_test)
print("정확도:{}".format(accuracy_score(y_test,y_pred)))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

정확도:0.9
[[ 9  0  0]
 [ 0  8  0]
 [ 0  3 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.73      1.00      0.84         8
 Iris-virginica       1.00      0.77      0.87        13

       accuracy                           0.90        30
      macro avg       0.91      0.92      0.90        30
   weighted avg       0.93      0.90      0.90        30



In [31]:
# finding optimal K 
k = 10
acc_list = []
for k in range(k):
    classifier = KNeighborsClassifier(n_neighbors=k+1).fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc = acc.round(2)
    acc_list.append(acc)

acc_list

[0.97, 0.93, 0.97, 0.9, 0.97, 0.9, 0.9, 0.9, 0.9, 0.9]